### ISSUE TITLE
Can't set slash command

### ISSUE THREAD

**Issue by HidemaruOwO** [Comamoca/teshitakun#2]
Running `deno run -A mod.ts` will log this error.
Because can't set slash command.
How can I resolve this error?

### Environment
- CPU: M1
- OS: macOS
- Deno version: 1.26.0

```bash
ERROR Helpers > Error: [400] The request was improperly formatted, or the server couldn't understand it.  
    at Object.runMethod (https://deno.land/x/discordeno@13.0.0-rc45/rest/runMethod.ts:28:9)
    at upsertApplicationCommands (https://deno.land/x/discordeno@13.0.0-rc45/helpers/interactions/commands/upsertApplicationCommands.ts:22:33)
    at Object.converted.<computed> [as upsertApplicationCommands] (https://deno.land/x/discordeno@13.0.0-rc45/bot.ts:371:7)
    at updateCommands (file:///Users/hidemaru/Code/teshitakun/src/utils/helpers.ts:56:23)
    at file:///Users/hidemaru/Code/teshitakun/mod.ts:54:7
```

**Comment by HidemaruOwO** [comment]
修正したのでレビューお願いします
https://github.com/Comamoca/teshitakun/pull/3
